import type { Metadata } from "next";
import { Anek_Tamil } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const anekTamil = Anek_Tamil({
  variable: "--font-anek-tamil",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anekTamil.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
